### PR TITLE
content/ssh: Add "git credential manager" to the SSH page.

### PR DESCRIPTION
**Pull request by rkdarst**
- This is based on my best knowledge but I haven't fully tested.
- I have tested on Windows.
- Review
  - Do we want to offer both options?
  - What are the risks?

### CODE REVIEW

**Comment by rkdarst** [comment]
Preview: https://coderefinery.github.io/installation/branch/rkdarst--gcm-setup/ssh/
I think this is starting to look good.

**Comment by bast** [comment]
It is good to offer this. But do we need to adjust the verification script which only tests the SSH part?

**Comment by rkdarst** [comment]
Oh yes... hm.  I can try to work on it.

**Comment by rkdarst** [comment]
I think it will work now.  It doesn't promise to verify things, but show's it configured.  I don't know how to fully automate the verification yet
- try cloning a private repo - goes to browser, but clone fails.  how to test?  needs some knowledge of what to expect, I think.
- try cloning public repo: doesn't use it
- ...

**Review by bast — APPROVED** [review]
I think this is a big improvement and we can merge.

**Pull request merged**
