### PR TITLE
Snakemake on Windows requires snakemake-minimal

### PR DESCRIPTION
**Pull request by rkdarst**
- Thanks to @annefou for the hint that solved it.
- I don't know how WSL vs native anaconda affects things, etc.  Or if
  this is even the right answer... please discuss.

### CODE REVIEW

**Comment by wikfeldt** [comment]
are you sure that Windows users really need to install snakemake-minimal? I haven't observed this in a workshop for windows users, and the official installation instructions don't mention it (https://snakemake.readthedocs.io/en/stable/getting_started/installation.html)

**Comment by rkdarst** [comment]
I'm not sure at all... I just know that Anne gave the suggestion is
zulip and it seemed to work.  Someone should investigate.

The direct problem was that the pygraphviz dependency wasn't available
for install via conda, but snakemake-minimal worked.  Could it be a
native vs WSL issue?  I think some people installed via pip and it
worked.

**Comment by bast** [comment]
I am unsure whether merge or not?

**Comment by rkdarst** [comment]
On Fri, May 31, 2019 at 01:59:54AM -0700, Radovan Bast wrote:
> I am unsure whether merge or not?

Let's wait and see if someone understands what is going on, in the
mean time the open request provides hints for others and documentation
on a problem.

**Comment by annefou** [comment]
Snakemake depends on pygraphviz which is not available for windows in "standard" conda channels this is why we only install snakemake-minimal on windows.

There is one version for windows at https://anaconda.org/marufr/pygraphviz (I have never tried it).

**Comment by blankdots** [comment]
I was also faced with installation issues of `snakemake` on `python 3.7` namely this: https://bitbucket.org/snakemake/snakemake/issues/934/installation-failed-in-python-37
Was solved by following this comment https://github.com/pytries/datrie/issues/52#issuecomment-464977050

**Comment by bast** [comment]
My understanding is that this PR needs to be amended?

**Comment by rkdarst** [comment]
I don't know... there were multiple issues, one about datrie, maybe one about this which is a bit questionable.  Really, I opened it because with `git-pr` it was easier to make a bad PR than a vague issue.  I know long-running open PRs aren't good, but this could be seen as an issue noting something until later...

I still don't know what the "right" solution is for sure, beyond Anne's knowledge.

**Comment by bast** [comment]
The Datrie one is out of scope of this PR AFAICS. I am happy to merge if it makes things better, also OK to park.

**Comment by bast** [comment]
@annefou what do you recommend we do with this PR :-) if follow-up actions are needed, can you please summarize what they are?

**Comment by annefou** [comment]
I would definitely recommend to merge this PR. We alwasy use snakemake-minimal on Windows as for instance pygraphviz  is not available for windows in standard conda channels.

**Comment by annefou** [comment]
Here is what you get if you try to install snakemake on windows:
PackagesNotFoundError: The following packages are not available from current channels:

  - snakemake -> imagemagick[version='>=7.0']
  - snakemake -> pygraphviz

**Comment by wikfeldt** [comment]
i think we can merge this PR. 

One alternative would be to recommend snakemake-minimal for all platforms, for simplicity's sake, but then osx/linux users would miss out on the feature to generate DAG images (i think that's what pygraphviz contributes)

**Comment by wikfeldt** [comment]
creating DAGs *is* still in the material. We could remove it and then recommend snakemake-minimal for all platforms. Advantage would be that it's simpler to recommend only one conda package, and possibly we would avoid some installation issues even on macs and linuxes, but drawback that participants (not on Win) can't create DAGs.

I guess this connects with how much snakemake we want to teach. I enjoy teaching snakemake and my feeling is that many participants have really found it useful. Of course it's not the right tool for everyone, but the same is true for e.g. pytest and jupyter. We teach one tool in a given category, and point out that there are other tools out there that might fit other use cases better (other testing frameworks, other notebooks (e.g. for R), other workflow frameworks).  

So my opinion is that we should not cut down snakemake to only bare minimum, and that we should keep an exercise on it, but that the lesson should still not be dominated by snakemake.
This might be easier to achieve if we follow Richards good suggestion to split into project organization and workflow parts

**Comment by wikfeldt** [comment]
so my suggestion *for now* is that we merge this PR as-is. The installation instructions (after merging) say that `snakemake-minimal` and `snakemake`  are two possible packages, but the former is required on Windows. So people running into issues on mac or linux will likely think of trying snakemake-minimal

**Comment by bast** [comment]
OK. Merging.

The DAG is nice to see and I agree it's nice to keep if it does not complicate installation too much.

Snakemake is a really nice tool and I am not trying to remove it. We need to offer good alternatives for the R community also and we know about this. Indeed the same can be said about pytest and that is one of the next things on my list to open up towards other communities and user profiles.

**Pull request merged**
