### PR TITLE
First version of installation verification script

### LINKED ISSUE #218: Verification bash script
We had some people come to the workshop without having set up SSH keys. Small problems with the installation can be helped with during the workshop, but the sooner it's caught, the easier it is to schedule time to fix it. What I suggest is that a bash verification script could be included that would run some tests and then print something like:

```
[✓] Git $VERSION installed
[✓] Anaconda $VERSION installed or [-] Anacode $VERSION may be too old
[✓] CodeRefinery Anaconda environment created
[✓] SSH installed
[✓] SSH key generated
[✘] SSH key set up with GitHub (see: https://coderefinery.github.io/xxx)
```

It could even ask for the GitHub username and test the SSH key had been added. At the beginning of the workshop we could ask people to run it so we could identify who has a partial install and help them e.g. in a break.

### PR DESCRIPTION
**Pull request by samumantha**
See also discussion in #218 

* installation_verification_[week1,week2,full_workshop].sh scripts added (full_workshop is same as week1 + week2 together, so if you change one, please also adapt the other)
* if you know bash, then better not to read it ;) I am still very much bash beginner
* seems to do what it is supposed to, but more testing required (!) -> therefore draft!

Scripts are supposed to do:
week1:
* check that git is installed and show the version, if not it exits the script and shows link on how to get git installed
* check that ssh keys are setup correctly with github, if not exits the script and shows link on how to set it up
week2:
* check that conda is installed and show version, if not it exits and shows link on how to install conda; if it is installed it checks if there is an environment with name coderefinery, if not it asks if user created the env under diffferent name, if that is not found then exit and shows link to how to create envirornment
full workshop: all of the above
 
Can of course be done nicer, so if you have time, please take over :)

Can be run for example like this: `curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/samumantha/installation/swi_verification_script/content/installation_verification_full_workshop.sh | bash`

Could maybe be moved to a better place also?

closes #218

### CODE REVIEW

**Comment by samumantha** [comment]
Btw, i did like very much the suggestion with clear check marks etc in the issue, but it seems that not all shells can render the same thing correctly as a checkmark, so left it out. 

There could maybe be a bit more empty space around to make it clear where the output starts/ends?

And now, that conda environment finding is moved to executing only when conda is found, maybe the exits on failure to find x could also be removed again? 

Not sure what would make most sense here?

**Comment by bast** [comment]
Thanks so much for your work! I will test.

**Comment by bast** [comment]
Working on it. I will add small changes (if needed) to the PR.

**Comment by bast** [comment]
Still working on it ... I will test and then also un-draft and merge so you can ignore my updates here.

**Comment by bast** [comment]
Safe bash settings were bad idea of mine. I will soon revert and add more changes.

**Comment by bast** [comment]
I will add text about it on the page in a separate commit/PR. Thanks again for this great work and also for the attention to detail in terms of conda env name.

**Pull request merged**
